# Generated by Django 4.1.7 on 2023-03-09 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='support',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=120, null=True, verbose_name='İsim')),
                ('email', models.CharField(blank=True, max_length=120, null=True, verbose_name='Email Adress')),
                ('subject', models.CharField(blank=True, max_length=120, null=True, verbose_name='Konu')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mesaj')),
            ],
        ),
    ]
