# Generated by Django 4.1.7 on 2023-03-09 10:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0002_adminmessage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adminmessage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='adminmessage',
            name='subject',
        ),
        migrations.RemoveField(
            model_name='adminmessage',
            name='user',
        ),
        migrations.AddField(
            model_name='adminmessage',
            name='support',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='support.support'),
            preserve_default=False,
        ),
    ]
